### ISSUE TITLE
dlquantizer bug 

### ISSUE THREAD

**Issue by sedurCode** [mathworks/Baseline-MATLAB-DCASE#2]
The baseline code is currently broken at the quantization section at line 123 with the following error:

> Warning: The following error was caught while executing 'dlquantization.internal.src.workflowcontrollers.ValidationController' class destructor:
> Dot indexing is not supported for variables of this type.
> Error in dlquantization.internal.src.validators.Validator/cleanup
> Error in dlquantization.internal.src.workflowcontrollers.ValidationController/cleanup
> Error in dlquantization.internal.src.workflowcontrollers.ValidationController/delete
> 
> )
>         end
> Error in dlquantization.internal.quantizerapp.ui.receiver.ExecuteActionReceiver/runLocal (line 28)
>                 [successFlag, diagnostic] = action.execute(workflowSetting);
> Error in dlquantization.internal.quantizerapp.ui.receiver.Receiver/run (line 18)
>             this.runLocal(response, datasetConnector);
> Error in dlquantization.internal.quantizerapp.ui.Command/execute (line 34)
>             this.Receiver.run(this.Response, this.DatasetConnector);
> Error in dlquantization.internal.quantizerapp.ui.executeCommand (line 26)
>         command.execute();
> Error in dlquantizer/validate
> Error in LiveEditorEvaluationHelperE983163144 (line 123)
> valResults = validate(quantObj,augimdsTest,quantOpts);
> Error in dlquantizer\validate 
> Dot indexing is not supported for variables of this type.

[This error might be related to other reports of the dlquantizer being broken.](https://uk.mathworks.com/matlabcentral/answers/794302-dlquantizer-workflow-failed-when-running-example-code?s_tid=ta_ans_results)

**Comment by BrianHemmat** [comment]
Hi Simon,
I was not able to reproduce this error on my machine.
The mex -setup for C++ is also required for this workflow. You may need to run `mex -setup cpp`. 
Here is a reference:
https://www.mathworks.com/help/matlab/matlab_external/changing-default-compiler.html
Do let me know if that fixes it for you and I will update the example with explicit instructions.
Thanks for posting these issues!
